OUTPUT_DIR: "/home/zqx_tesla/home/zqx_tesla/PersonReID/PersonReID2/RPPS/Output/cuhk-da"
INPUT:
  DATASET: "CUHK-SYSU"
  TDATASET: "PRW"
  DATA_ROOT: "/home/zqx_tesla/home/zqx_tesla/PersonReID/data1/CUHK-SYSU"
  TDATA_ROOT: "/home/zqx_tesla/home/zqx_tesla/PersonReID/data1/PRW"
  BATCH_SIZE_TRAIN: 2 #4
SOLVER:
  MAX_EPOCHS: 24
  LR_DECAY_MILESTONES: [16]
  BASE_LR: 0.0024
  LW_DA_INS: 0.98
MODEL:
  DA_HEADS:
    DA_IMG_LOSS_WEIGHT: 1.0
    DA_INS_LOSS_WEIGHT: 1.0
    DA_CST_LOSS_WEIGHT: 0.1
  UPDATE_FACTOR:
    ONLINE: 0.2
    OFFLINE: 0.2
EVAL_PERIOD: 1
TARGET_REID_START: 8
EPS_P: 0.98
